services:
  - type: web
    name: walkapp-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: JWT_SECRET
        generateValue: true
